name: Build Web Application Server
on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # checkout source
      - uses: actions/checkout@v2
      # install jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # setup settings.xml of maven
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      # packaging project
      - name: Build with Maven
        run: mvn -P tomcat9 -B package --file was-dist/pom.xml
      # get project version
      - name: Bump Version
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # upload package to AWS S3
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'was-dist/target/lena-work'
          destination_dir: 'openlena/was'
      # setup Container Image Build module
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Setup repository access info
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # get repository name
      - id: repository
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      # build docker container image and push to repository
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./was-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=amazonlinux:2
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_amazonlinux2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./was-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=centos:8
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_centos8
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./was-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=centos:7
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_centos7
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./was-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=rockylinux/rockylinux:8.4
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_rocky8
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./was-containerization/Dockerfile
          push: true
          build-args: |
            FROM_IMAGE=ubuntu:18.04
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_ubuntu18.04
